version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: myloginsrv-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: myloginsrv-php
    volumes:
      - .:/var/www/html
