version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: myloginsrv-php
    volumes:
      - ./web:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html

  nginx:
    image: nginx:latest
    container_name: myloginsrv-nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
