services:
  blur-faceselect:
    container_name: faceselect-blur-auto
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    environment:
      - PYTHONUNBUFFERED=1
