services:

 watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    profiles: ["update"]
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 14400
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
