services:
  faceblur-man:
    container_name: faceblur-man
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7863:7861"          # <host>:<container>
    restart: always          # startet Container nach Host-Reboot automatisch
    logging:
      driver: "none"         # keine Docker-Logs sammeln
    environment:
      - PYTHONUNBUFFERED=1   # direktes Logging in Konsole
    # volumes:               # nur für aktive Entwicklung nötig
    #   - .:/app
    #   - /app/node_modules  # Beispiel, falls Frontend-Deps
    # develop:               # entfernen, wenn kein Tilt/Forge o.ä. verwendet
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app