UI:
  Scrollbar: true
  Zoom: false
  Theme: grayscale
  Language: de
  TimeZone: ""
  StartPage: default
Search:
  BatchSize: 0
  ListView: true
  ShowTitles: true
  ShowCaptions: true
Albums:
  Order:
    Album: oldest
    Folder: added
    Moment: oldest
    State: newest
    Month: oldest
  Download:
    Name: share
    Disabled: false
    Originals: true
    MediaRaw: false
    MediaSidecar: false
Maps:
  Animate: 0
  Style: ""
Features:
  Account: true
  Albums: true
  Archive: true
  Delete: true
  Download: true
  Edit: true
  Estimates: true
  Favorites: true
  Files: true
  Folders: true
  Import: true
  Labels: true
  Library: true
  Logs: true
  Calendar: true
  Moments: true
  People: false
  Places: true
  Private: true
  Ratings: true
  Reactions: true
  Review: true
  Search: true
  Services: false
  Settings: true
  Share: true
  Upload: true
  Videos: true
Import:
  Path: /
  Move: false
Index:
  Path: /
  Convert: true
  Rescan: true
  SkipArchived: false
Stack:
  UUID: true
  Meta: true
  Name: true
Share:
  Title: ""
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: true
  MediaSidecar: true
Templates:
  Default: index.gohtml
